# Generated by Django 5.2.1 on 2025-08-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="api_key",
            field=models.CharField(
                default="tJixMNatDHr96ZP09U9V55pp9oVYtAktmwVoibF7wIgbzjug5M3xGCz6C61s2GDqL3OosYmR3KJDLvNCoiJ7QsfOIj99AUptQWtXB51QmMMqv94o5ICCntwvHmMZoichcC4G4V1zGpfGC9knmG6xyT",
                max_length=150,
                unique=True,
                verbose_name="API Key",
            ),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="token",
            field=models.CharField(
                default="izfQAEiokHe9rixnorlKd8QDgDxPJgWQ7AihptoRISe3QUmYyxrIiQlOKUR6sJX2PdxEd6dXSSi1fMzHWhgjyL0SDlaWvFgmrvqp5AwRvG2pD6g4ut6x7x6oyzNIZrLOH1uP2CPE9KjPrgUVz7DCN3",
                max_length=150,
                unique=True,
                verbose_name="Token",
            ),
        ),
    ]
