# Generated by Django 5.2.1 on 2025-08-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_usermodel_api_key_usermodel_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="api_key",
            field=models.CharField(max_length=150, unique=True, verbose_name="API Key"),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="token",
            field=models.CharField(max_length=150, unique=True, verbose_name="Token"),
        ),
    ]
