# Generated by Django 5.2.1 on 2025-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_usermodel_api_key_alter_usermodel_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="api_key",
            field=models.CharField(
                default="kIsSvteO2nxz2XSCNzdSlq3Ndi53SsiRJdDNN0bzfoYDC1IA09u93nN1jiUhGJ99eeGhRsBNzw6bEH2kr331vXAafjBwGAXs37yk",
                max_length=100,
                unique=True,
                verbose_name="API Key",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="token",
            field=models.CharField(
                default="1BgGiplJQ1Llnxc0bEf362Dbc5GjXO1rx5OXdupdedzdQGQYiGC02tGGpLzUQ2l3sM7GImx9nxgvZCEUUYfdXThAWZvB97ikuZ6P",
                max_length=100,
                unique=True,
                verbose_name="Token",
            ),
        ),
    ]
