# Generated by Django 5.2.1 on 2025-08-26 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_usermodel_api_key_alter_usermodel_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="token_active_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Token Active Date"
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="api_key",
            field=models.CharField(
                default="WArcdjpwvok49XMW2UdKFgQaLyac8bDeKLG7UBkSxYVX3EI9vus3U3G84LjQrRLNY05xyRikisMuGVuxKmg5hx5NEeIk61PzINDU",
                max_length=100,
                unique=True,
                verbose_name="API Key",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="token",
            field=models.CharField(
                default="51FcKum0hv2WkG6nxwe3JONrjhG5PQBnkm69s5CEOpLHc0HHdwguUeoCF2AF9EbNnpcCQjcf2yfwNNkNpXjWS65bziVyrM0qWZOo",
                max_length=100,
                unique=True,
                verbose_name="Token",
            ),
        ),
    ]
