# Generated by Django 5.2.1 on 2025-08-26 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_usermodel_token_active_date_alter_usermodel_api_key_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="api_key",
            field=models.CharField(
                default="skp31QyMT3vMuaLGVNU2kSSvBoF7JYArApXz3LW3hd1oncQDS3OSPhlree3wDw4SPymOujpSDS0vArhMMyp4pfsE9P1x2PoG1wYo",
                max_length=100,
                unique=True,
                verbose_name="API Key",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="token",
            field=models.CharField(
                default="0amlwGxQwVUaorrHnLd8Fz6tjoQ8KCGWNfEjKDAjrVyZlScL0YAQQM6kuUp0cuu58PHW7YtaCCUQlxKUa1qFRHmQrIS2Rb95mWQe",
                max_length=100,
                unique=True,
                verbose_name="Token",
            ),
        ),
        migrations.CreateModel(
            name="QrCodeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qrcode", models.ImageField(upload_to="qr_codes/")),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
